#!/bin/bash

SCRIPT_CMAKE_PROGRAM="${CMAKE_PROGRAM}"
SCRIPT_CONAN_PROGRAM="${CONAN_PROGRAM}"

SCRIPT_SOURCE_PREFIX="${PWD}"
SCRIPT_BUILD_PREFIX="${SCRIPT_SOURCE_PREFIX}"'\build'
SCRIPT_INSTALL_PREFIX="${SCRIPT_BUILD_PREFIX}"'\install'

SCRIPT_MSVC_RUNTIME_LIBRARY='MultiThreadedDLL'
SCRIPT_BUILD_TYPE='Release'
SCRIPT_GENERATOR='Visual Studio 16 2019'

"${SCRIPT_CMAKE_PROGRAM}" -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING="${SCRIPT_MSVC_RUNTIME_LIBRARY}" -DCMAKE_BUILD_TYPE:STRING="${SCRIPT_BUILD_TYPE}" -DCMAKE_INSTALL_PREFIX:PATH="${SCRIPT_INSTALL_PREFIX}" -DCMAKE_CONAN_PROGRAM:FILEPATH="${SCRIPT_CONAN_PROGRAM}" -G "${SCRIPT_GENERATOR}" -S "${SCRIPT_SOURCE_PREFIX}" -B "${SCRIPT_BUILD_PREFIX}" &&\
"${SCRIPT_CMAKE_PROGRAM}" --build "${SCRIPT_BUILD_PREFIX}" --target "library-conan-install" &&\
"${SCRIPT_CMAKE_PROGRAM}" -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING="${SCRIPT_MSVC_RUNTIME_LIBRARY}" -DCMAKE_BUILD_TYPE:STRING="${SCRIPT_BUILD_TYPE}" -DCMAKE_INSTALL_PREFIX:PATH="${SCRIPT_INSTALL_PREFIX}" -DCMAKE_CONAN_PROGRAM:FILEPATH="${SCRIPT_CONAN_PROGRAM}" -G "${SCRIPT_GENERATOR}" -S "${SCRIPT_SOURCE_PREFIX}" -B "${SCRIPT_BUILD_PREFIX}" &&\
"${SCRIPT_CMAKE_PROGRAM}" --build "${SCRIPT_BUILD_PREFIX}" --target "install" &&\
"${SCRIPT_CMAKE_PROGRAM}" --build "${SCRIPT_BUILD_PREFIX}" --target "library-conan-export-testing" &&\
"${SCRIPT_CMAKE_PROGRAM}" --build "${SCRIPT_BUILD_PREFIX}" --target "test-conan-install" &&\
"${SCRIPT_CMAKE_PROGRAM}" -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING="${SCRIPT_MSVC_RUNTIME_LIBRARY}" -DCMAKE_BUILD_TYPE:STRING="${SCRIPT_BUILD_TYPE}" -DCMAKE_INSTALL_PREFIX:PATH="${SCRIPT_INSTALL_PREFIX}" -DCMAKE_CONAN_PROGRAM:FILEPATH="${SCRIPT_CONAN_PROGRAM}" -G "${SCRIPT_GENERATOR}" -S "${SCRIPT_SOURCE_PREFIX}" -B "${SCRIPT_BUILD_PREFIX}" &&\
"${SCRIPT_CMAKE_PROGRAM}" --build "${SCRIPT_BUILD_PREFIX}" --target "integration-tests-interface-executable" &&\
"${SCRIPT_CMAKE_PROGRAM}" --build "${SCRIPT_BUILD_PREFIX}" --target "integration-tests" &&\
"${SCRIPT_CMAKE_PROGRAM}" --build "${SCRIPT_BUILD_PREFIX}" --target "library-conan-export" &&\
(tput setaf 2 && echo 'BUILD_SUCCESSFUL') ||\
(tput setaf 1 && echo 'BUILD_FAILED')
