function(
    set_not_found_package_names
    variableName
)
    if("${ARGC}" GREATER_EQUAL "2")
        set("start" "1")
        math(EXPR "stop" "${ARGC} - 1")
        foreach(i RANGE "${start}" "${stop}")
            set(argument "${ARGV${i}}")
            if(NOT "${${argument}_FOUND}")
                list(APPEND value "${argument}")
            endif()
        endforeach()
    endif()
    set("${variableName}" "${value}" PARENT_SCOPE)
endfunction()

macro(get_targets_recursive targets dir)
    get_property(subdirectories DIRECTORY ${dir} PROPERTY SUBDIRECTORIES)
    foreach(subdir ${subdirectories})
        get_targets_recursive(${targets} ${subdir})
    endforeach()
    get_property(current_targets DIRECTORY ${dir} PROPERTY BUILDSYSTEM_TARGETS)
    list(APPEND ${targets} ${current_targets})
endmacro()

function(set_targets var)
    set(targets)
    get_targets_recursive(targets ${CMAKE_CURRENT_SOURCE_DIR})
    set(${var} ${targets} PARENT_SCOPE)
endfunction()
